server:
  port: 8080

spring:
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true 
    serialization: 
      indent_output: true
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_SINGLE_VALUE_AS_ARRAY: true
    default-property-inclusion: non_empty
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: system.developer.rus@gmail.com
    password: 04Divepa-
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false


  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: Qwerty123
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true

  jpa:
    openInView: false
    show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true

  data:
    jpa:
      repositories.enabled: true

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    ru.marketplace: DEBUG
  file: app.log

